name: Issues

on:
  issues:
    types: [opened, reopened, closed, deleted]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: IRC notification
        uses: rectalogic/notify-irc@v1
        with:
          channel: '#hammerspoon'
          nickname: 'HSGHA'
          message: |
            ${{ github.actor }} ${{ github.event }} ${{ github.url }}
